In [1]:
# Import dependencies.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import gmaps
import requests

from config import geoapify_key

In [2]:
selected_cities = pd.read_csv("WeatherPy_vacation.csv")
selected_cities

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,1,Rikitea,PF,79.72,broken clouds,-23.1203,-134.9692,Chez Bianca & Benoit
1,3,Sambava,MG,76.44,light rain,-14.2667,50.1667,Royal Sava Hôtel
2,4,Bandarbeyla,SO,80.65,few clouds,9.4942,50.8122,No hotel found
3,5,Kapaa,US,80.92,light rain,22.0752,-159.3190,Pono Kai Resort
4,6,Ciudad Valles,MX,70.21,clear sky,21.9833,-99.0167,Hotel Riviera
...,...,...,...,...,...,...,...,...
265,699,Dwarka,IN,77.32,clear sky,22.2394,68.9678,The Dwarika Hotel
266,701,Sindi,IN,77.88,overcast clouds,20.8000,78.8667,No hotel found
267,702,Chicama,PE,77.54,overcast clouds,-7.8447,-79.1469,No hotel found
268,704,Nagar Karnul,IN,81.12,overcast clouds,16.4821,78.3247,No hotel found
269,705,Simao,CN,75.47,clear sky,22.7886,100.9748,Marvelous Land Hotel

In [3]:
my_itenary = selected_cities
my_itenary

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,1,Rikitea,PF,79.72,broken clouds,-23.1203,-134.9692,Chez Bianca & Benoit
1,3,Sambava,MG,76.44,light rain,-14.2667,50.1667,Royal Sava Hôtel
2,4,Bandarbeyla,SO,80.65,few clouds,9.4942,50.8122,No hotel found
3,5,Kapaa,US,80.92,light rain,22.0752,-159.3190,Pono Kai Resort
4,6,Ciudad Valles,MX,70.21,clear sky,21.9833,-99.0167,Hotel Riviera
...,...,...,...,...,...,...,...,...
265,699,Dwarka,IN,77.32,clear sky,22.2394,68.9678,The Dwarika Hotel
266,701,Sindi,IN,77.88,overcast clouds,20.8000,78.8667,No hotel found
267,702,Chicama,PE,77.54,overcast clouds,-7.8447,-79.1469,No hotel found
268,704,Nagar Karnul,IN,81.12,overcast clouds,16.4821,78.3247,No hotel found
269,705,Simao,CN,75.47,clear sky,22.7886,100.9748,Marvelous Land Hotel

In [4]:
my_itenary.reset_index(drop=True,inplace=True)
my_itenary

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,1,Rikitea,PF,79.72,broken clouds,-23.1203,-134.9692,Chez Bianca & Benoit
1,3,Sambava,MG,76.44,light rain,-14.2667,50.1667,Royal Sava Hôtel
2,4,Bandarbeyla,SO,80.65,few clouds,9.4942,50.8122,No hotel found
3,5,Kapaa,US,80.92,light rain,22.0752,-159.3190,Pono Kai Resort
4,6,Ciudad Valles,MX,70.21,clear sky,21.9833,-99.0167,Hotel Riviera
...,...,...,...,...,...,...,...,...
265,699,Dwarka,IN,77.32,clear sky,22.2394,68.9678,The Dwarika Hotel
266,701,Sindi,IN,77.88,overcast clouds,20.8000,78.8667,No hotel found
267,702,Chicama,PE,77.54,overcast clouds,-7.8447,-79.1469,No hotel found
268,704,Nagar Karnul,IN,81.12,overcast clouds,16.4821,78.3247,No hotel found
269,705,Simao,CN,75.47,clear sky,22.7886,100.9748,Marvelous Land Hotel

In [5]:
city_a = (my_itenary.loc[0]["Lat"],my_itenary.loc[0]["Lng"])
city_b = (my_itenary.loc[1]["Lat"],my_itenary.loc[1]["Lng"])
city_c = (my_itenary.loc[2]["Lat"],my_itenary.loc[2]["Lng"])
city_d = (my_itenary.loc[6]["Lat"],my_itenary.loc[6]["Lng"])

city_a
city_b
city_c
city_d

(20.6274, -87.0799)

In [6]:
selectedItenary_df = my_itenary[(my_itenary["City"] == "Malacacheta") | (my_itenary["City"] == "Rio Verde De Mato Grosso") | (my_itenary["City"] == "Jatai") | (my_itenary["City"] == "Jales")]  
# selectedItenary_df.append(my_itenary.loc[4:6])
selectedItenary_df

Empty DataFrame
Columns: [City_ID, City, Country, Max Temp, Current Description, Lat, Lng, Hotel Name]
Index: []

In [7]:
import gmaps.datasets

gmaps.configure(api_key=geoapify_key)

fig = gmaps.figure()

city_a2city_d = gmaps.directions_layer(city_a, city_d, waypoints=[city_b, city_c])

fig.add_layer(city_a2city_d)
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
import gmaps

gmaps.configure(api_key=geoapify_key)

fig = gmaps.figure()

#Adding markers.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in selectedItenary_df.iterrows()]

#Create the marker for each city.
locations = selectedItenary_df[["Lat","Lng"]]
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

#direction Layer
city_a2city_d = gmaps.directions_layer(city_a, city_d, waypoints=[city_b, city_c])
fig.add_layer(city_a2city_d)
fig

Figure(layout=FigureLayout(height='420px'))